# Generated by Django 4.1 on 2022-08-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflearn_lecture', '0004_mytext_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytext',
            name='img_url',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
